"""added cascade logic to recurrence types

Revision ID: 02bd24adc948
Revises: 03dd844eb029
Create Date: 2026-03-10 12:31:10.639889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bd24adc948'
down_revision: Union[str, Sequence[str], None] = '03dd844eb029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('discharge_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_chat_history_patient_id'), table_name='chat_history')
    op.create_index(op.f('ix_chat_history_discharge_id'), 'chat_history', ['discharge_id'], unique=False)
    op.drop_constraint(op.f('chat_history_patient_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'discharge_history', ['discharge_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('chat_history', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_patient_id_fkey'), 'chat_history', 'patients', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_history_discharge_id'), table_name='chat_history')
    op.create_index(op.f('ix_chat_history_patient_id'), 'chat_history', ['patient_id'], unique=False)
    op.drop_column('chat_history', 'discharge_id')
    # ### end Alembic commands ###
