"""added cascade logic to recurrence types

Revision ID: 03dd844eb029
Revises: c3d4e5f6a7b8
Create Date: 2026-03-10 12:00:50.440324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dd844eb029'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_sessions', sa.Column('discharge_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_telegram_sessions_discharge_id'), 'telegram_sessions', ['discharge_id'], unique=False)
    op.drop_constraint(op.f('telegram_sessions_patient_id_fkey'), 'telegram_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_sessions', 'discharge_history', ['discharge_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('telegram_sessions', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_sessions', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'telegram_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('telegram_sessions_patient_id_fkey'), 'telegram_sessions', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_telegram_sessions_discharge_id'), table_name='telegram_sessions')
    op.drop_column('telegram_sessions', 'discharge_id')
    # ### end Alembic commands ###
