"""added latest alembic version file

Revision ID: 05b1c298f40a
Revises: 9a1154bbc2a1
Create Date: 2026-03-10 12:37:47.894049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b1c298f40a'
down_revision: Union[str, Sequence[str], None] = '9a1154bbc2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_sessions', 'discharge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_sessions', 'discharge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
