"""added error reasons columns

Revision ID: 0cdbeb06f6e5
Revises: 51570389a0e0
Create Date: 2026-03-13 15:09:59.673502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdbeb06f6e5'
down_revision: Union[str, Sequence[str], None] = '51570389a0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discharge_history', 'error_type')
    op.drop_column('discharge_history', 'failure_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discharge_history', sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('discharge_history', sa.Column('error_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
