"""changed whatsapp_id to telegram_id

Revision ID: 208fe9db2901
Revises: 5476eb9ef823
Create Date: 2026-03-06 16:32:42.116253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208fe9db2901'
down_revision: Union[str, Sequence[str], None] = '5476eb9ef823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'patients',
    sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false())
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_verified')
    # ### end Alembic commands ###
