"""added error reasons columns

Revision ID: 51570389a0e0
Revises: cef254f38244
Create Date: 2026-03-13 15:07:48.405177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51570389a0e0'
down_revision: Union[str, Sequence[str], None] = 'cef254f38244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discharge_history', 'failed_at_type')
    op.drop_column('discharge_history', 'failed_at_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discharge_history', sa.Column('failed_at_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('discharge_history', sa.Column('failed_at_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
