"""changed whatsapp_id to telegram_id

Revision ID: 5476eb9ef823
Revises: d9c864692a82
Create Date: 2026-03-06 16:30:54.612128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5476eb9ef823'
down_revision: Union[str, Sequence[str], None] = 'd9c864692a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.drop_column('patients', 'whatsapp_id')
    op.alter_column('refresh_tokens', 'device_type',
               existing_type=postgresql.ENUM('MOBILE', 'DESKTOP', name='devicetype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'device_type',
               existing_type=postgresql.ENUM('MOBILE', 'DESKTOP', name='devicetype'),
               nullable=False)
    op.add_column('patients', sa.Column('whatsapp_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'telegram_chat_id')
    # ### end Alembic commands ###
