"""added telegram_session table

Revision ID: 58933f4cf963
Revises: ce32dfb20477
Create Date: 2026-03-06 17:24:53.109146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58933f4cf963'
down_revision: Union[str, Sequence[str], None] = 'ce32dfb20477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('session_status', sa.Enum('NEW', 'AWAIT_OTP', 'AWAIT_MOBILE', 'VERIFIED', name='sessionstatus'), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('otp', sa.String(), nullable=True),
    sa.Column('otp_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_sessions_id'), 'telegram_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_sessions_telegram_id'), 'telegram_sessions', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_sessions_telegram_id'), table_name='telegram_sessions')
    op.drop_index(op.f('ix_telegram_sessions_id'), table_name='telegram_sessions')
    op.drop_table('telegram_sessions')
    # ### end Alembic commands ###
