"""created tables

Revision ID: 616ce7d24181
Revises: b8e2d2970b75
Create Date: 2026-03-03 15:25:45.249848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616ce7d24181'
down_revision: Union[str, Sequence[str], None] = 'b8e2d2970b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('speciality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('recurrence_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('every_n_days', sa.Integer(), nullable=True),
    sa.Column('start_date_for_every_n_days', sa.Date(), nullable=True),
    sa.Column('cycle_take_days', sa.Integer(), nullable=True),
    sa.Column('cycle_skip_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrence_types_id'), 'recurrence_types', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency_of_dose_per_day', sa.Integer(), nullable=False),
    sa.Column('dosing_days', sa.Integer(), nullable=True),
    sa.Column('recurrence_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('form_of_medicine', sa.Enum('TABLET', 'CAPSULE', 'SYRUP', 'INJECTION', 'DROPS', 'CREAM', 'OINTMENT', 'INHALER', 'POWDER', 'OTHER', name='medicineform'), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrence_types.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_doctor_id'), 'medications', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_recurrence_id'), 'medications', ['recurrence_id'], unique=False)
    op.create_table('patient_doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_doctor_doctor_id'), 'patient_doctor', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_doctor_id'), 'patient_doctor', ['id'], unique=False)
    op.create_index(op.f('ix_patient_doctor_patient_id'), 'patient_doctor', ['patient_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hashed', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_type', sa.Enum('MOBILE', 'DESKTOP', name='devicetype'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hashed')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_patient_id'), 'refresh_tokens', ['patient_id'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('before_breakfast', sa.Boolean(), nullable=True),
    sa.Column('after_breakfast', sa.Boolean(), nullable=True),
    sa.Column('before_lunch', sa.Boolean(), nullable=True),
    sa.Column('after_lunch', sa.Boolean(), nullable=True),
    sa.Column('before_dinner', sa.Boolean(), nullable=True),
    sa.Column('after_dinner', sa.Boolean(), nullable=True),
    sa.Column('latest_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_notify_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_id'), 'medication_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_medication_schedules_medication_id'), 'medication_schedules', ['medication_id'], unique=True)
    op.add_column('reports', sa.Column('report_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_name')
    op.drop_index(op.f('ix_medication_schedules_medication_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_refresh_tokens_patient_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_patient_doctor_patient_id'), table_name='patient_doctor')
    op.drop_index(op.f('ix_patient_doctor_id'), table_name='patient_doctor')
    op.drop_index(op.f('ix_patient_doctor_doctor_id'), table_name='patient_doctor')
    op.drop_table('patient_doctor')
    op.drop_index(op.f('ix_medications_recurrence_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_doctor_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_recurrence_types_id'), table_name='recurrence_types')
    op.drop_table('recurrence_types')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
