"""created bill and patient tables

Revision ID: 713659d29595
Revises: 61d432b37315
Create Date: 2026-03-03 12:47:33.591222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713659d29595'
down_revision: Union[str, Sequence[str], None] = '61d432b37315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('whatsapp_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bill_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_patient_id'), 'bills', ['patient_id'], unique=False)
    op.create_table('bill_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_description_bill_id'), 'bill_description', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_description_id'), 'bill_description', ['id'], unique=False)
    op.create_index(op.f('ix_report_descriptions_patient_id'), 'report_descriptions', ['patient_id'], unique=False)
    op.drop_constraint(op.f('report_descriptions_report_id_fkey'), 'report_descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'report_descriptions', 'reports', ['report_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'report_descriptions', 'patients', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'patients', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_constraint(None, 'report_descriptions', type_='foreignkey')
    op.drop_constraint(None, 'report_descriptions', type_='foreignkey')
    op.create_foreign_key(op.f('report_descriptions_report_id_fkey'), 'report_descriptions', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_report_descriptions_patient_id'), table_name='report_descriptions')
    op.drop_index(op.f('ix_bill_description_id'), table_name='bill_description')
    op.drop_index(op.f('ix_bill_description_bill_id'), table_name='bill_description')
    op.drop_table('bill_description')
    op.drop_index(op.f('ix_bills_patient_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
