"""added urls in discharge_history

Revision ID: 898469434cce
Revises: 05b1c298f40a
Create Date: 2026-03-10 15:08:13.991421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898469434cce'
down_revision: Union[str, Sequence[str], None] = '05b1c298f40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discharge_history', sa.Column('discharge_summary_url', sa.String(), nullable=True))
    op.add_column('discharge_history', sa.Column('patient_friendly_summary_url', sa.String(), nullable=True))
    op.add_column('discharge_history', sa.Column('insurance_ready_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discharge_history', 'insurance_ready_url')
    op.drop_column('discharge_history', 'patient_friendly_summary_url')
    op.drop_column('discharge_history', 'discharge_summary_url')
    # ### end Alembic commands ###
