"""added password to patient

Revision ID: b79ac07d8065
Revises: 8c4a5cb4dbd5
Create Date: 2026-03-03 17:01:13.768656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79ac07d8065'
down_revision: Union[str, Sequence[str], None] = '8c4a5cb4dbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patients_email_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.create_unique_constraint(op.f('patients_email_key'), 'patients', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
