"""added FK in bill_description

Revision ID: b8e2d2970b75
Revises: 713659d29595
Create Date: 2026-03-03 13:13:42.754550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e2d2970b75'
down_revision: Union[str, Sequence[str], None] = '713659d29595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_description', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bill_description_patient_id'), 'bill_description', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'bill_description', 'patients', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill_description', type_='foreignkey')
    op.drop_index(op.f('ix_bill_description_patient_id'), table_name='bill_description')
    op.drop_column('bill_description', 'patient_id')
    # ### end Alembic commands ###
