"""added telegram_session table

Revision ID: ce32dfb20477
Revises: 208fe9db2901
Create Date: 2026-03-06 17:23:11.963045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce32dfb20477'
down_revision: Union[str, Sequence[str], None] = '208fe9db2901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'telegram_chat_id')
    op.drop_column('patients', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('telegram_chat_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
