"""added error reasons columns

Revision ID: cef254f38244
Revises: a26b96d4c6f5
Create Date: 2026-03-13 13:24:46.107687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef254f38244'
down_revision: Union[str, Sequence[str], None] = 'a26b96d4c6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discharge_history', sa.Column('failed_at_type', sa.String(length=20), nullable=True))
    op.add_column('discharge_history', sa.Column('failed_at_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discharge_history', 'failed_at_index')
    op.drop_column('discharge_history', 'failed_at_type')
    # ### end Alembic commands ###
