"""added password to patient

Revision ID: d2667f78868a
Revises: 616ce7d24181
Create Date: 2026-03-03 16:59:20.450934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2667f78868a'
down_revision: Union[str, Sequence[str], None] = '616ce7d24181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_description_patient_id'), table_name='bill_description')
    op.drop_constraint(op.f('bill_description_patient_id_fkey'), 'bill_description', type_='foreignkey')
    op.drop_column('bill_description', 'patient_id')
    op.add_column('patients', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'password_hash')
    op.add_column('bill_description', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bill_description_patient_id_fkey'), 'bill_description', 'patients', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_bill_description_patient_id'), 'bill_description', ['patient_id'], unique=False)
    # ### end Alembic commands ###
