name: Call FastAPI Cron

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call FastAPI endpoint
        run: |
          echo "Calling API at $(date)"
          curl -L --fail --show-error --verbose https://fastapi-post-discharge-system-backe.vercel.app/